kind: pipeline
name: default

steps:
- name: deploy
  image: wipac/docker:dind-python
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    IMAGE_NAME: wipac/monitoring-scripts
    DOCKERHUB_USER:
      from_secret: DOCKERHUB_USER
    DOCKERHUB_PASS:
      from_secret: DOCKERHUB_PASS
    GITHUB_USER:
      from_secret: GITHUB_USER
    GITHUB_PASS:
      from_secret: GITHUB_PASS
  commands:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - python deploy.py

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

trigger:
  branch:
  - master
  event:
  - push
  - cron