FROM icecube/icetray:icetray-main-cuda11.1 as tensorflow2.4.1

MAINTAINER IceCube <developers@icecube.wisc.edu>

WORKDIR /root

# build tensorflow
RUN pip3 install tensorflow==2.4.1

# build pytorch
RUN pip3 install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

# I3DeepIce stuff 
RUN git clone https://github.com/icecube/low-level-ml.git low-level-ml && \
    cp -r low-level-ml/low_level_ml lib && \
    git clone https://github.com/IceCubeOpenSource/i3deepice.git i3deepice && \
    cp -r i3deepice/i3deepice lib

# provide the entry point to run commands
ENTRYPOINT ["/bin/bash", "/usr/local/icetray/env-shell.sh", "exec"]
CMD ["/bin/bash"]
