FROM icecube/icetray:icetray-main-cuda11.6 as icecube_ml

MAINTAINER IceCube <developers@icecube.wisc.edu>

# build tensorflow
RUN pip3 install tensorflow==2.9.1

#graphnet stuff
ARG TORCH=1.12.0
ARG PYG=2.0.4
ARG CUDA=cu116

RUN pip3 install torch==${TORCH}+${CUDA} -f https://download.pytorch.org/whl/torch/ && \
    pip3 install torch-cluster -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html && \
    pip3 install torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html && \
    pip3 install torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html  && \
    pip3 install torch-spline-conv -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html  && \
    pip3 install torch-geometric==${PYG}

RUN pip3 install --upgrade setuptools>=59.5
RUN pip3 install git+https://github.com/icecube/graphnet.git@v0.2.0#egg=graphnet

WORKDIR /usr/local/icetray
# I3DeepIce stuff
RUN git clone https://github.com/icecube/low-level-ml.git low-level-ml && \
    cp -r low-level-ml/low_level_ml lib && \
    git clone https://github.com/IceCubeOpenSource/i3deepice.git i3deepice && \
    cp -r i3deepice/i3deepice lib

WORKDIR /root

# provide the entry point to run commands
ENTRYPOINT ["/bin/bash", "/usr/local/icetray/env-shell.sh", "exec"]
CMD ["/bin/bash"]
