FROM icecube/icetray:icetray-main-cuda11.1 as tensorflow2.4.1

MAINTAINER IceCube <developers@icecube.wisc.edu>

WORKDIR /root

# install nuflux
RUN pip install --user git+https://github.com/icecube/nuflux

# build tensorflow
RUN pip3 install tensorflow==2.4.1

# build pytorch
RUN pip3 install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

# stage in icetray from the previous build
COPY --from=install-tf /usr/local/icetray /usr/local/icetray

# provide the entry point to run commands
ENTRYPOINT ["/bin/bash", "/usr/local/icetray/env-shell.sh", "exec"]
CMD ["/bin/bash"]
