version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.7.2
              environment:
                LTA_MONGODB_URL: mongodb://localhost:27017
            - image: circleci/mongo:3.7.9-ram
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                pytest tests
    deploy:
        resource_class: large
        docker:
            - image: circleci/buildpack-deps:stretch
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - run: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
                python deploy.py
workflows:
    version: 2
    build_and_test:
        jobs:
            - deploy:
                context: docker
                filters:
                    branches:
                        only: master
    release:
        jobs:
            - deploy:
                context: docker
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v?\d+\.\d+\.\d+$/
