#### Create a "developer" base for Rocky 9
# Why Rocky. NVIDIA uses Rocky 8 as the base image
# This is mostly meant as a image for grid computing

FROM rockylinux:9 as base-devel

MAINTAINER IceCube <developers@icecube.wisc.edu>

WORKDIR /root

RUN dnf install -y epel-release
RUN dnf install -y dnf-plugins-core

RUN dnf config-manager --enable -y crb
RUN dnf config-manager --enable -y epel
RUN dnf config-manager --enable -y extras

# Not available yet
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then dnf -y install http://repo.opensciencegrid.org/osg/3.6/osg-3.6-el9-release-latest.rpm; fi

RUN dnf -y group install "Development Tools" "Scientific Support"

RUN dnf -y --allowerasing install \
           # astropy-tools \
           bc \
           binutils \
           binutils-devel \
           blas \
           blas-devel \
           boost-date-time \
           boost-devel \
           boost-system \ 
           boost-thread \
           boost-filesystem \
           boost-program-options \
           boost-regex \
           boost-iostreams \
           boost-python3-devel \
           bzip2-devel \
           cfitsio-devel \
           cmake \
           cppzmq-devel \
           curl \
           davix-devel \
           dcap-devel \
           fontconfig \
           gcc \
           gcc-c++ \
           gcc-gfortran \
           git \
           glib2-devel \
           graphviz \
           gfal2 \ 
           gsl-devel \
           json-c-devel \
           hdf5 \
           lapack \
           lapack-devel \
           libaec-devel \
           libarchive \
           libattr-devel \
           libgfortran \
           libicu \
           libtool \
           libtool-ltdl \
           libtool-ltdl-devel \
           libuuid-devel \
           libxml2 \
           libxml2-devel \
           make \
           ocl-icd \ 
           ocl-icd-devel \
           openssl \
           # osg-wn-client \
           p7zip \
           p7zip-plugins \
           # python3-astropy \
           python3-devel \
           python3-numpy \
           # python3-matplotlib\
           python3-scipy \
           # redhat-lsb \
           # redhat-lsb-core \
           srm-ifce-devel \
           # starlink-pal \
           # stashcache-client \
           suitesparse \
           wget \
           xrootd-client-devel \
           zlib-devel 
           
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then dnf -y install osg-wn-client stashcache-client condor libquadmath; fi && rm -f /etc/grid-security/certificates/*.r0


RUN dnf clean all

# install photospline
RUN curl -L https://github.com/icecube/photospline/archive/refs/tags/v2.1.0.tar.gz | tar xz && \
  cd photospline-2.1.0 && cmake . -DCMAKE_INSTALL_PREFIX=/usr/local && make && make install

RUN curl -L https://github.com/icecube/nuflux/archive/refs/tags/v2.0.4.tar.gz | tar xz && \
    cd nuflux-2.0.4 && \
    meson build && \
    ninja -C build install && \
    pip install .

# required directories
RUN for MNTPOINT in \
        /cvmfs \
    ; do \
        mkdir -p $MNTPOINT ; \
    done
