#### Create a "developer" base

FROM almalinux:8.5 as base-devel

MAINTAINER IceCube <developers@icecube.wisc.edu>

WORKDIR /root
#
#Add the Powertools
RUN dnf install -y 'dnf-command(config-manager)'
RUN dnf config-manager --set-enabled powertools

# add epel
RUN dnf install -y epel-release

RUN dnf groupinstall -y 'Development Tools'
RUN dnf install -y cmake wget rsync python3-devel boost-devel boost-python3-devel \
	gsl-devel bzip2-devel zlib-devel python3-numpy python3-scipy fftw-devel \
	xz-devel openblas-devel libarchive-devel erfa-devel hdf5-devel suitesparse-devel \
	ncurses-devel cfitsio-devel libzstd-devel gmp-devel libxml2-devel python3-zmq \
	opencl-headers cppzmq-devel ocl-icd-devel python3-matplotlib python3-numexpr \
	python3-h5py python3-pyyaml python3-pandas ninja-build opencl-filesystem

#setup pocl http://portablecl.org/download.html
RUN dnf install -y hwloc-devel llvm-devel clang-devel
RUN wget http://portablecl.org/downloads/pocl-1.7.tar.gz && tar zxvf pocl-1.7.tar.gz && \
	cd pocl-1.7 && mkdir build && cd build && cmake ../ && make && make install && cd
RUN ln -s /usr/local/etc/OpenCL/vendors/pocl.icd /etc/OpenCL/vendors 

RUN wget https://github.com/Starlink/pal/releases/download/v0.9.8/pal-0.9.8.tar.gz && \
	tar zxf pal-0.9.8.tar.gz && cd pal-0.9.8 && \
	./configure --prefix=/usr/local --without-starlink && make install && cd

RUN wget https://github.com/zeromq/cppzmq/archive/master.tar.gz && \
    tar -zxf master.tar.gz && cd cppzmq-master && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr . && make install && cd

# install photospline
RUN curl -L https://github.com/icecube/photospline/archive/refs/tags/v2.0.7.tar.gz | tar xz &&\
  cd photospline-2.0.7 && cmake . -DCMAKE_INSTALL_PREFIX=/usr/local && make && make install
