FROM icecube/icetray:combo-main-base as slim

MAINTAINER IceCube <developers@icecube.wisc.edu>

WORKDIR /root

# stage in icetray
COPY --from=icecube/icetray:combo-main-install /usr/local/icetray /usr/local/icetray
COPY --from=icecube/icetray:combo-main-install /opt/i3-data /opt/i3-data

# set environment variables
ENV I3_DATA /opt/i3-data
ENV I3_TESTDATA /opt/i3-data/i3-test-data
ENV TMPDIR /scratch

# create the scratch directory
RUN mkdir -p /scratch

# provide the entry point to run commands
ENTRYPOINT ["/bin/bash", "/usr/local/icetray/env-shell.sh", "exec"]
CMD ["/bin/bash"]
