FROM icecube/icetray:icetray-main-tensorflow2.4.1 as icecube_ml

MAINTAINER IceCube <developers@icecube.wisc.edu>

COPY --from=install-tf /usr/local/icetray /usr/local/icetray

WORKDIR /usr/local/icetray
# I3DeepIce stuff 
RUN git clone https://github.com/icecube/low-level-ml.git low-level-ml && \
    cp -r low-level-ml/low_level_ml lib && \
    git clone https://github.com/IceCubeOpenSource/i3deepice.git i3deepice && \
    cp -r i3deepice/i3deepice lib

#graphnet stuff
ARG TORCH=1.9.1
ARG PYG=2.0.1
ARG CUDA=cu111 

RUN pip3 install torch==${TORCH}+${CUDA} -f https://download.pytorch.org/whl/cpu/torch_stable.html && \
    pip3 install torch-cluster -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html && \
    pip3 install torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html && \
    pip3 install torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html  && \
    pip3 install torch-spline-conv -f https://data.pyg.org/whl/torch-${TORCH}+${CUDA}.html  && \
    pip3 install torch-geometric==${PYG}

RUN pip3 install git+https://github.com/icecube/graphnet.git


# provide the entry point to run commands
ENTRYPOINT ["/bin/bash", "/usr/local/icetray/env-shell.sh", "exec"]
CMD ["/bin/bash"]
