ARG VERSION=current
FROM icecube/icetray-ml:icetray-${VERSION}-cuda11.8-cudnn8-ubuntu22.04

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade astropy
RUN pip3 install --ignore-installed PyYAML

RUN pip3 install --find-links https://download.pytorch.org/whl/torch_stable.html torch==2.0.1+cu118 --find-links https://data.pyg.org/whl/torch-2.0.0+cu118.html

RUN mkdir /src

RUN pip3 install -e git+https://github.com/icecube/graphnet.git#egg=graphnet[develop,torch]

RUN ls /root/src/graphnet

RUN cp -r /root/src/graphnet /src/

RUN groupadd --gid 1000 graphnet-dev-team && useradd --uid 1000 --gid graphnet-dev-team --create-home --shell /bin/bash graphnet-dev

RUN chown -R graphnet-dev:graphnet-dev-team /home/graphnet-dev && \
    chown -R graphnet-dev:graphnet-dev-team /src

USER graphnet-dev

RUN export PYTHONPATH="/src/graphnet/src":$PYTHONPATH

# Default command for executing container.
CMD [ "/bin/bash" ]
