ARG VERSION=current
FROM icecube/icetray-ml:icetray-${VERSION}-cuda12.1-cudnn8-ubuntu22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && apt-get install -y software-properties-common

RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main'
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y clang-16 lldb-16 lld-16 libllvm-16-ocaml-dev libllvm16 llvm-16 llvm-16-dev llvm-16-doc llvm-16-examples llvm-16-runtime clang-16 clang-tools-16 clang-16-doc libclang-common-16-dev libclang-16-dev libclang1-16 clang-format-16 python3-clang-16 clangd-16 clang-tidy-16 

RUN pip3 install --upgrade pip
RUN pip3 install numpy wheel packaging requests opt_einsum 
RUN pip3 install keras_preprocessing --no-deps

RUN pip3 install tensorflow==2.13.0

# Default command for executing container.
CMD [ "/bin/bash" ]
