ARG VERSION=current
FROM icecube/icetray-ml:icetray-cuda11.8-cudann8-icetray-${VERSION}-ubuntu22.04

RUN apt-get update && sudo apt-get install -y llvm-16 clang-16


RUN pip3 install --upgrade pip
RUN pip3 install numpy wheel packaging requests opt_einsum 
RUN pip3 install keras_preprocessing --no-deps

RUN pip3 install tensorflow==2.13.0

# Default command for executing container.
CMD [ "/bin/bash" ]