#### Create a "developer" base

FROM ubuntu:20.04 as base-devel

MAINTAINER IceCube <developers@icecube.wisc.edu>

WORKDIR /root

# install system packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  tar wget rsync gzip bzip2 xz-utils liblzma5 liblzma-dev zlib1g zlib1g-dev \
  less build-essential cmake libbz2-dev libzstd-dev \
  libxml2-dev subversion git libboost-python1.71-dev \
  libboost-system1.71-dev libboost-thread1.71-dev libboost-numpy1.71-dev \
  libboost-date-time1.71-dev libboost-serialization1.71-dev \
  libboost-filesystem1.71-dev libboost-program-options1.71-dev \
  libboost-regex1.71-dev libboost-iostreams1.71-dev libgsl0-dev \
  libcdk5-dev libarchive-dev python3-scipy \
  python3-urwid python3-numpy python3-matplotlib \
  python3-numexpr cython3 python3-cffi python3-requests \
  python3-healpy python3-urllib3 python3-jsonschema \
  python3-zmq python3-pymysql python3-yaml python3-dev python3-pip \
  zlib1g-dev liberfa-dev libstarlink-pal-dev \
  libopenblas-dev libsprng2-dev \
  libsuitesparse-dev libfftw3-dev \
  libcfitsio-dev libhdf5-dev libhealpix-cxx-dev \
  opencl-headers opencl-c-headers opencl-clhpp-headers \
  ocl-icd-libopencl1 ocl-icd-opencl-dev \
  libzmq5 libzmq3-dev libzmqpp-dev libzmqpp4 \
  nano vim sudo man-db lsb-release \
  && apt-get clean

RUN wget https://github.com/zeromq/cppzmq/archive/master.tar.gz && \
    tar -zxf master.tar.gz && cd cppzmq-master && \
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr . && make install
