FROM icecube/icetray:combo-stable-base-devel as install

MAINTAINER IceCube <developers@icecube.wisc.edu>

WORKDIR /root

# set up test data directory
RUN mkdir /opt/i3-data
ENV I3_DATA /opt/i3-data
RUN mkdir /opt/i3-data/i3-test-data
ENV I3_TESTDATA /opt/i3-data/i3-test-data

# check out icetray
RUN mkdir /root/combo && mkdir /root/combo/build
COPY icetray /root/combo/src

# build icetray
WORKDIR /root/combo/build
RUN cmake /root/combo/src \
      -DCMAKE_BUILD_TYPE=Release \
      -DINSTALL_TOOL_LIBS=OFF \
      -DUSE_GFILT=OFF \
      -DCMAKE_INSTALL_PREFIX=/usr/local/icetray \
      -DUSE_PYTHON3=OFF \
    && make -j4

# install icetray
RUN make install

# provide the entry point to run commands
ENTRYPOINT ["/bin/bash", "/root/combo/build/env-shell.sh", "exec"]
CMD ["/bin/bash"]
