ARG TARGET_UBUNTU=ubuntu20.04
ARG CMAKE_CXX_STANDARD=11
FROM icecube/icetray-base:devel-${TARGET_UBUNTU} as install

MAINTAINER IceCube <developers@icecube.wisc.edu>

WORKDIR /root

# set up test data directory
RUN mkdir /opt/i3-data
RUN mkdir /opt/i3-data/i3-test-data

# check out icetray
RUN mkdir /root/icetray && mkdir /root/icetray/build

## GitHub clone
## Most recent release..
ARG VERSION=v1.4.1
RUN --mount=type=secret,id=GHTOKEN GHTOKEN=$(cat /run/secrets/GHTOKEN) && \
    git clone -c advice.detachedHead=false --depth 1 -b ${VERSION} https://oauth:${GHTOKEN}@github.com/icecube/icetray.git /usr/local/icetray_src
RUN echo ${VERSION} > /usr/local/icetray_src/version_tag

# build icetray
WORKDIR /root/icetray/build
RUN cmake /usr/local/icetray_src \
      -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD} \
      -DCMAKE_BUILD_TYPE=Release \
      -DINSTALL_TOOL_LIBS=OFF \
      -DCMAKE_INSTALL_PREFIX=/usr/local/icetray \
    && make -j4

# install icetray
RUN make install

# set environment variables
ENV I3_DATA /opt/i3-data
ENV I3_TESTDATA /opt/i3-data/i3-test-data
ENV TMPDIR /scratch

# install photon tables
RUN mkdir -p /opt/i3-data/photon-tables/splines
#    wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/ems_mie_z20_a10.abs.fits       http://prod-exe.icecube.wisc.edu/spline-tables/ems_mie_z20_a10.abs.fits && \
#    wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/ems_mie_z20_a10.prob.fits      http://prod-exe.icecube.wisc.edu/spline-tables/ems_mie_z20_a10.prob.fits

# install baseline GCDs
#RUN mkdir /opt/i3-data/baseline_gcds && \
#    wget -nv -N -t 5 -P /opt/i3-data/baseline_gcds -r -l 1 -A *.i3* -nd https://icecube:skua@convey.icecube.wisc.edu/data/user/followup/baseline_gcds/ && \
#    chmod -R u+rwX,go+rX,go-w /opt/i3-data/baseline_gcds

# install test data
RUN rsync -vrlpt --delete code.icecube.wisc.edu::Offline/test-data/trunk/ /opt/i3-data/i3-test-data/

# build the matplotlib font cache (prevents warnings about the font cache on startup)
RUN python3 -c 'from matplotlib import pyplot'

# create the scratch directory
RUN mkdir -p /scratch


WORKDIR /root
# Cleanup!
RUN rm -rf /root/icetray
# provide the entry point to run commands
ENTRYPOINT ["/bin/bash", "/usr/local/icetray/env-shell.sh", "exec"]
CMD ["/bin/bash"]
