ARG TARGET_UBUNTU=ubuntu20.04
ARG VERSION=current
ARG ARCH=X64
FROM icecube/icetray:icetray-devel-${VERSION}-${TARGET_UBUNTU}-${ARCH} as icetray-build
FROM icecube/icetray-base:prod-${TARGET_UBUNTU} as prod

MAINTAINER IceCube <developers@icecube.wisc.edu>

WORKDIR /root

# stage in icetray
COPY --from=icetray-build /usr/local/icetray /usr/local/icetray
COPY --from=icetray-build /usr/local/icetray_src /usr/local/icetray_src
RUN mkdir /opt/i3-data

# set environment variables
ENV I3_DATA /opt/i3-data
#ENV I3_TESTDATA /opt/i3-data/i3-test-data
ENV TMPDIR /scratch

# install photon tables
RUN mkdir -p /opt/i3-data/photon-tables/splines
#    wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/ems_mie_z20_a10.abs.fits       http://prod-exe.icecube.wisc.edu/spline-tables/ems_mie_z20_a10.abs.fits && \
#    wget -nv -t 5 -O /opt/i3-data/photon-tables/splines/ems_mie_z20_a10.prob.fits      http://prod-exe.icecube.wisc.edu/spline-tables/ems_mie_z20_a10.prob.fits

# install baseline GCDs
#RUN mkdir /opt/i3-data/baseline_gcds && \
#    wget -nv -N -t 5 -P /opt/i3-data/baseline_gcds -r -l 1 -A *.i3* -nd https://icecube:skua@convey.icecube.wisc.edu/data/user/followup/baseline_gcds/ && \
#    chmod -R u+rwX,go+rX,go-w /opt/i3-data/baseline_gcds

# build the matplotlib font cache (prevents warnings about the font cache on startup)
RUN python3 -c 'from matplotlib import pyplot'

# create the scratch directory
RUN mkdir -p /scratch

# provide the entry point to run commands
ENTRYPOINT ["/bin/bash", "/usr/local/icetray/env-shell.sh", "exec"]
CMD ["/bin/bash"]
