ARG TARGET_UBUNTU=ubuntu20.04
# EKB: change back to icecube
FROM blaufuss/icetray:base-devel-${TARGET_UBUNTU} as install

MAINTAINER IceCube <developers@icecube.wisc.edu>

WORKDIR /root

# set up test data directory
RUN mkdir /opt/i3-data
ENV I3_DATA /opt/i3-data
RUN mkdir /opt/i3-data/i3-test-data
ENV I3_TESTDATA /opt/i3-data/i3-test-data

# check out icetray
RUN mkdir /root/icetray && mkdir /root/icetray/build

## GitHub clone
## Most recent release..
ARG VERSION=v1.4.1
ARG GHTOKEN
RUN git clone -c advice.detachedHead=false --depth 1 -b ${VERSION} https://oauth:${GHTOKEN}@github.com/icecube/icetray.git /root/icetray/src

# build icetray
WORKDIR /root/icetray/build
RUN cmake /root/icetray/src \
      -DCMAKE_BUILD_TYPE=Release \
      -DINSTALL_TOOL_LIBS=OFF \
      -DCMAKE_INSTALL_PREFIX=/usr/local/icetray \
    && make -j2

# install icetray
RUN make install

WORKDIR /root
# provide the entry point to run commands
ENTRYPOINT ["/bin/bash", "/usr/local/icetray/env-shell.sh", "exec"]
CMD ["/bin/bash"]
