name: build_nu_souces_images

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'neutrino_sources/Dockerfile*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push  neutrin-source base 20.04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: neutrino_sources/Dockerfile
          build-args: |
            GHTOKEN=${{ secrets.GHTOKEN }}
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/nu-sources:base-current-ubuntu20.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/nu-sources:base-current-ubuntu22.04-${{ env.current_date }}
