name: build_base_images

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'base_ubuntu/Dockerfile*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push base devel 20 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: base_ubuntu/Dockerfile_base-devel-20.04
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-devel-ubuntu20.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-devel-ubuntu20.04-${{ steps.date.outputs.date }},
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-devel-ubuntu20.04-latest,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-devel,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-devel-latest
      -
        name: Build and push base 20 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: base_ubuntu/Dockerfile_base-20.04
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-ubuntu20.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-ubuntu20.04-${{ steps.date.outputs.date }},
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-ubuntu20.04-latest,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-latest
      -
        name: Build and push base devel 22 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: base_ubuntu/Dockerfile_base-devel-22.04
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-devel-ubuntu22.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-devel-ubuntu22.04-${{ steps.date.outputs.date }},
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-devel-ubuntu22.04-latest
      -
        name: Build and push base devel 22 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: base_ubuntu/Dockerfile_base-22.04
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-ubuntu22.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-ubuntu22.04-${{ steps.date.outputs.date }},
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:main-base-ubuntu22.04-latest
