name: build_icetray_ml

env:
  ICETRAY_VERSION: v1.7.2

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'icecube_ml/Dockerfile*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push icetray ml cuda 11.6 for 20 04
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     file: icecube_ml/Dockerfile_ubuntu_20.04_cuda11.6
      #     build-args: |
      #       VERSION=${{ env.ICETRAY_VERSION }}
      #     tags: >
      #       icecube/icetray-ml:icetray-cuda11.6-${{ env.ICETRAY_VERSION }}-ubuntu20.04,
      #       icecube/icetray-ml:icetray-cuda11.6-current-ubuntu20.04,
      #       icecube/icetray-ml:icetray-cuda11.6-${{ env.ICETRAY_VERSION }}-ubuntu20.04-${{ env.current_date }}
      -
        name: Build and push icetray ml cuda 11.8 for 22 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: icecube_ml/Dockerfile_ubuntu_22.04_cuda11.8_cudann8
          build-args: |
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            icecube/icetray-ml:icetray-cuda11.8-cudnn8-icetray-${{ env.ICETRAY_VERSION }}-ubuntu22.04,
            icecube/icetray-ml:icetray-cuda11.8-cudnn8-icetray-current-ubuntu22.04,
            icecube/icetray-ml:icetray-cuda11.8-cudnn8-icetray-${{ env.ICETRAY_VERSION }}-ubuntu22.04-${{ env.current_date }}
      -
        name: Build and push icetray ml cuda 11.8 for 22 04 with graphnet
        uses: docker/build-push-action@v3
        with:
          push: true
          file: icecube_ml/Dockerfile_ubuntu_22.04_cuda11.8_cudann8_icetray_graphnet
          build-args: |
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            icecube/icetray-ml:icetray-cuda11.8-cudnn8-icetray-${{ env.ICETRAY_VERSION }}-graphnet-ubuntu22.04,
            icecube/icetray-ml:icetray-cuda11.8-cudnn8-icetray-current-graphnet-ubuntu22.04,
            icecube/icetray-ml:icetray-cuda11.8-cudnn8-icetray-${{ env.ICETRAY_VERSION }}-graphnet-ubuntu22.04-${{ env.current_date }}
      -
        name: Build and push icetray ml cuda 11.8 for 22 04 with tensorflow
        uses: docker/build-push-action@v3
        with:
          push: true
          file: icecube_ml/Dockerfile_ubuntu_22.04_cuda11.8_cudann8_icetray_tensorflow
          build-args: |
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            icecube/icetray-ml:icetray-cuda11.8-cudnn8-icetray-${{ env.ICETRAY_VERSION }}-tf-ubuntu22.04,
            icecube/icetray-ml:icetray-cuda11.8-cudnn8-icetray-current-tf-ubuntu22.04,
            icecube/icetray-ml:icetray-cuda11.8-cudnn8-icetray-${{ env.ICETRAY_VERSION }}-tf-ubuntu22.04-${{ env.current_date }}
      # -
      #   name: Build and push icetray ml  20 04
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     file: icecube_ml/Dockerfile_ubuntu_20.04_icecube_ml
      #     build-args: |
      #       VERSION=${{ env.ICETRAY_VERSION }}
      #     tags: >
      #       icecube/icetray-ml:icetray-ml-base-${{ env.ICETRAY_VERSION }}-ubuntu20.04,
      #       icecube/icetray-ml:icetray-ml-base-current-ubuntu20.04,
      #       icecube/icetray-ml:icetray-ml-base-${{ env.ICETRAY_VERSION }}-ubuntu20.04-${{ env.current_date }}
