name: build_icetray_images_arm

env:
  ICETRAY_VERSION: v1.4.1

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'install_icetray/Dockerfile*'

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, macos, ARM64, m1]]
#     runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#       -
#         name: Build and push icetray install 20 04
#         uses: docker/build-push-action@v3
#         with:
#           push: true
#           file: install_icetray/Dockerfile_install
#           platforms: linux/arm64/v8
#           build-args: |
#             GHTOKEN=${{ secrets. PERSONAL_ACCESS_TOKEN }}
#             TARGET_UBUNTU=ubuntu20.04
#             VERSION=${{ env.ICETRAY_VERSION }}
#           tags: >
#             icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu20.04,
#             icecube/icetray:icetray-devel-current-ubuntu20.04,
#             icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu20.04-${{ env.current_date }}
      -
        name: Build and push icetray install 22 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: install_icetray/Dockerfile_install
          platforms: linux/arm64/v8
          build-args: |
            GHTOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
            TARGET_UBUNTU=ubuntu22.04
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu22.04,
            icecube/icetray:icetray-devel-current-ubuntu22.04,
            icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu22.04-${{ env.current_date }}
#       -
#         name: Build and push icetray prod 20 04
#         uses: docker/build-push-action@v3
#         with:
#           push: true
#           file: install_icetray/Dockerfile_prod
#           platforms: linux/arm64/v8
#           build-args: |
#             TARGET_UBUNTU=ubuntu20.04
#             VERSION=${{ env.ICETRAY_VERSION }}
#           tags: >
#             icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu20.04,
#             icecube/icetray:icetray-prod-current-ubuntu20.04,
#             icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu20.04-${{ env.current_date }}
      -
        name: Build and push icetray prod 22 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: install_icetray/Dockerfile_prod
          platforms: linux/arm64/v8
          build-args: |
            TARGET_UBUNTU=ubuntu22.04
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu22.04,
            icecube/icetray:icetray-prod-current-ubuntu22.04,
            icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu22.04-${{ env.current_date }}
