name: build_icetray_images

env:
  ICETRAY_VERSION: v1.4.1

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'install_icetray/Dockerfile*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push icetray install 20 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: install_icetray/Dockerfile_install
          build_args: >
            GHTOKEN=${{ secrets.GH_TOKEN }},
            TARGET_UBUNTU=ubuntu20.04,
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:${{ env.ICETRAY_VERSION }}-ubuntu20.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:${{ env.ICETRAY_VERSION }}-ubuntu20.04-${{ steps.date.outputs.date }}
      -
        name: Build and push icetray install 22 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: install_icetray/Dockerfile_install
          build_args: >
            GHTOKEN=${{ secrets.GH_TOKEN }},
            TARGET_UBUNTU=ubuntu22.04,
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:${{ env.ICETRAY_VERSION }}-ubuntu22.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:${{ env.ICETRAY_VERSION }}-ubuntu22.04-${{ steps.date.outputs.date }}
