name: build_icetray_ml

env:
  ICETRAY_VERSION: v1.13.0
  PUSH: true

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'icecube_ml/Dockerfile*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push icetray ml cuda 12.1 for 22 04
        uses: docker/build-push-action@v3
        with:
          push: ${{env.PUSH}}
          file: icecube_ml/Dockerfile_ubuntu_22.04_cuda11.8_cudann8
          build-args: |
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            icecube/icetray-ml:icetray-${{ env.ICETRAY_VERSION }}-cuda12.1-cudnn8-ubuntu22.04,
            icecube/icetray-ml:icetray-current-cuda12.1-cudnn8-ubuntu22.04,
            icecube/icetray-ml:icetray-${{ env.ICETRAY_VERSION }}-cuda12.1-cudnn8-ubuntu22.04-${{ env.current_date }}
      -
        name: Build and push icetray ml cuda 11.8 for 22 04 with graphnet
        uses: docker/build-push-action@v3
        with:
          push: ${{env.PUSH}}
          file: icecube_ml/Dockerfile_ubuntu_22.04_cuda11.8_cudann8_icetray_graphnet
          build-args: |
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            icecube/icetray-ml:icetray-${{ env.ICETRAY_VERSION }}-cuda11.8-cudnn8-graphnet-ubuntu22.04,
            icecube/icetray-ml:icetray-current-cuda11.8-cudnn8-graphnet-ubuntu22.04,
            icecube/icetray-ml:icetray-${{ env.ICETRAY_VERSION }}-cuda11.8-cudnn8-graphnet-ubuntu22.04-${{ env.current_date }}
      -
        name: Build and push icetray ml cuda 12.1 for 22 04 with tensorflow
        uses: docker/build-push-action@v3
        with:
          push: ${{env.PUSH}}
          file: icecube_ml/Dockerfile_ubuntu_22.04_cuda11.8_cudann8_icetray_tensorflow
          build-args: |
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            icecube/icetray-ml:icetray-${{ env.ICETRAY_VERSION }}-cuda12.1-cudnn8-tf-ubuntu22.04,
            icecube/icetray-ml:icetray-current-cuda12.1-cudnn8-tf-ubuntu22.04,
            icecube/icetray-ml:icetray-${{ env.ICETRAY_VERSION }}-cuda12.1-cudnn8-tf-ubuntu22.04-${{ env.current_date }}
      # -
      #   name: Build and push icetray ml cuda 12.1 for 22 04 with graphnet dev
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: ${{env.PUSH}}
      #     file: icecube_ml/Dockerfile_ubuntu_22.04_cuda11.8_cudann8_icetray_graphnet-devel
      #     build-args: |
      #       VERSION=${{ env.ICETRAY_VERSION }}
      #     tags: >
      #       icecube/icetray-ml:icetray-${{ env.ICETRAY_VERSION }}-cuda12.1-cudnn8-graphnet-ubuntu22.04-devel,
      #       icecube/icetray-ml:icetray-current-cuda12.1-cudnn8-graphnet-ubuntu22.04-devel,
      #       icecube/icetray-ml:icetray-${{ env.ICETRAY_VERSION }}-cuda12.1-cudnn8-graphnet-ubuntu22.04-devel-${{ env.current_date }}
      # -
      #   name: Build and push icetray ml for 22 04 rocm
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: ${{env.PUSH}}
      #     file: icecube_ml/Dockerfile_ubuntu_22.04_rocm5.7
      #     build-args: |
      #       VERSION=${{ env.ICETRAY_VERSION }}
      #     tags: >
      #       icecube/icetray-ml:icetray-${{ env.ICETRAY_VERSION }}-rocm5.7-ubuntu22.04-devel,
      #       icecube/icetray-ml:icetray-current-rocm5.7-ubuntu22.04-devel,
      #       icecube/icetray-ml:icetray-${{ env.ICETRAY_VERSION }}-rocm5.7-ubuntu22.04-devel-${{ env.current_date }}
      # -
      #   name: Build and push icetray ml for 22 04 pytorch
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: ${{env.PUSH}}
      #     file: icecube_ml/Dockerfile_ubuntu_22.04_cuda12.1_cudann_pytorch2.2.2
      #     build-args: |
      #       VERSION=${{ env.ICETRAY_VERSION }}
      #     tags: >
      #       icecube/icetray-ml:icetray-${{ env.ICETRAY_VERSION }}-cuda12.1-cudann-pytorch2.2.2-ubuntu22.04-devel,
      #       icecube/icetray-ml:icetray-current-cuda12.1-cudann-pytorch2.2.2-ubuntu22.04-devel,
      #       icecube/icetray-ml:icetray-${{ env.ICETRAY_VERSION }}-cuda12.1-cudann-pytorch2.2.2-ubuntu22.04-devel-${{ env.current_date }}
