name: build_icetray_images

env:
  ICETRAY_VERSION: v1.4.1

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'install_icetray/Dockerfile*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push icetray install 20 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: install_icetray/Dockerfile_install
          build-args: |
            GHTOKEN=${{ secrets.GHTOKEN }}
            TARGET_UBUNTU=ubuntu20.04
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu20.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:icetray-devel-current-ubuntu20.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu20.04-${{ steps.date.outputs.date }}
      -
        name: Build and push icetray install 22 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: install_icetray/Dockerfile_install
          build-args: |
            GHTOKEN=${{ secrets.GHTOKEN }}
            TARGET_UBUNTU=ubuntu22.04
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu22.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:icetray-devel-current-ubuntu22.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu22.04-${{ steps.date.outputs.date }}
      -
        name: Build and push icetray prod 20 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: install_icetray/Dockerfile_prod
          build-args: |
            TARGET_UBUNTU=ubuntu20.04
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu20.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:icetray-prod-current-ubuntu20.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu20.04-${{ steps.date.outputs.date }}
      -
        name: Build and push icetray prod 22 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: install_icetray/Dockerfile_prod
          build-args: |
            TARGET_UBUNTU=ubuntu22.04
            VERSION=${{ env.ICETRAY_VERSION }}
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu22.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:icetray-prod-current-ubuntu22.04,
            ${{ secrets.DOCKERHUB_USERNAME }}/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu22.04-${{ steps.date.outputs.date }}
