name: build_base_images

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'icetray_base/Dockerfile*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push base devel 20 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: icetray_base/Dockerfile_base-devel-20.04
          platforms: linux/amd64,linux/arm64/v8
          tags: >
            icecube/icetray-base:devel-ubuntu20.04,
            icecube/icetray-base:devel-ubuntu20.04-${{ env.current_date }}
      -
        name: Build and push base prod 20 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: icetray_base/Dockerfile_base-prod-20.04
          platforms: linux/amd64,linux/arm64/v8
          tags: >
            icecube/icetray-base:prod-ubuntu20.04,
            icecube/icetray-base:prod-ubuntu20.04-${{ env.current_date }}
      -
        name: Build and push base devel 22 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: icetray_base/Dockerfile_base-devel-22.04
          platforms: linux/amd64,linux/arm64/v8
          tags: >
            icecube/icetray-base:devel-ubuntu22.04,
            icecube/icetray-base:devel-ubuntu22.04-${{ env.current_date }}
      -
        name: Build and push base prod 22 04
        uses: docker/build-push-action@v3
        with:
          push: true
          file: icetray_base/Dockerfile_base-prod-22.04
          platforms: linux/amd64,linux/arm64/v8
          tags: >
            icecube/icetray-base:prod-ubuntu22.04,
            icecube/icetray-base:prod-ubuntu22.04-${{ env.current_date }}
            
      -
        name: Build and push base devel rocky 8
        uses: docker/build-push-action@v3
        with:
          push: true
          file: icetray_base/Dockerfile_base-devel-rocky8
          platforms: linux/amd64,linux/arm64/v8
          tags: >
            icecube/icetray-base:devel-rocky8,
            icecube/icetray-base:devel-rocky8-${{ env.current_date }}
      -
        name: Build and push base devel rocky 9
        uses: docker/build-push-action@v3
        with:
          push: true
          file: icetray_base/Dockerfile_base-devel-rocky9
          platforms: linux/amd64,linux/arm64/v8
          tags: >
            icecube/icetray-base:devel-rocky9,
            icecube/icetray-base:devel-rocky9-${{ env.current_date }}
