name: docker_manifest

env:
  ICETRAY_VERSION: v1.4.1

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'install_icetray/Dockerfile*'

jobs:
  manifest-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create and push manifest images install 20 04 IceTray Version
        uses: Noelware/docker-manifest-action@master # or use whatever version.
        with:
          base-image: icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu20.04
          extra-images: icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu20.04-X64,icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu20.04-ARM64
          push: true
      - name: Create and push manifest images install 20 04 Current Version
        uses: Noelware/docker-manifest-action@master # or use whatever version.
        with:
          base-image: icecube/icetray:icetray-devel-current-ubuntu20.04
          extra-images: icecube/icetray:icetray-devel-current-ubuntu20.04-X64,icecube/icetray:icetray-devel-current-ubuntu20.04-ARM64
          push: true
#       - name: Create and push manifest images install 20 04 Date Version
#         uses: Noelware/docker-manifest-action@master # or use whatever version.
#         with:
#           base-image: icecube/icetray:icetray-devel-current-ubuntu20.04-${{ env.current_date }}
#           extra-images: icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu20.04-X64-${{ env.current_date }},icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu20.04-ARM64-${{ env.current_date }}
#           push: true
          
      - name: Create and push manifest images install 22 04 IceTray Version
        uses: Noelware/docker-manifest-action@master # or use whatever version.
        with:
          base-image: icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu22.04
          extra-images: icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu22.04-X64,icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu22.04-ARM64
          push: true
      - name: Create and push manifest images install 22 04 Current Version
        uses: Noelware/docker-manifest-action@master # or use whatever version.
        with:
          base-image: icecube/icetray:icetray-devel-current-ubuntu22.04
          extra-images: icecube/icetray:icetray-devel-current-ubuntu22.04-X64,icecube/icetray:icetray-devel-current-ubuntu22.04-ARM64
          push: true
#       - name: Create and push manifest images install 22 04 Date Version
#         uses: Noelware/docker-manifest-action@master # or use whatever version.
#         with:
#           base-image: icecube/icetray:icetray-devel-current-ubuntu22.04-${{ env.current_date }}
#           extra-images: icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu22.04-X64-${{ env.current_date }},icecube/icetray:icetray-devel-${{ env.ICETRAY_VERSION }}-ubuntu22.04-ARM64-${{ env.current_date }}
#           push: true
          
      - name: Create and push manifest images prod 20 04 IceTray Version
        uses: Noelware/docker-manifest-action@master # or use whatever version.
        with:
          base-image: icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu20.04
          extra-images: icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu20.04-X64,icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu20.04-ARM64
          push: true
      - name: Create and push manifest images prod 20 04 Current Version
        uses: Noelware/docker-manifest-action@master # or use whatever version.
        with:
          base-image: icecube/icetray:icetray-prod-current-ubuntu20.04
          extra-images: icecube/icetray:icetray-prod-current-ubuntu20.04-X64,icecube/icetray:icetray-prod-current-ubuntu20.04-ARM64
          push: true
#       - name: Create and push manifest images prod 20 04 Date Version
#         uses: Noelware/docker-manifest-action@master # or use whatever version.
#         with:
#           base-image: icecube/icetray:icetray-prod-current-ubuntu20.04-${{ env.current_date }}
#           extra-images: icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu20.04-X64-${{ env.current_date }},icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu20.04-ARM64-${{ env.current_date }}
#           push: true
          
      - name: Create and push manifest images prod 22 04 IceTray Version
        uses: Noelware/docker-manifest-action@master # or use whatever version.
        with:
          base-image: icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu22.04
          extra-images: icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu22.04-X64,icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu22.04-ARM64
          push: true
      - name: Create and push manifest images prod 22 04 Current Version
        uses: Noelware/docker-manifest-action@master # or use whatever version.
        with:
          base-image: icecube/icetray:icetray-prod-current-ubuntu22.04
          extra-images: icecube/icetray:icetray-prod-current-ubuntu22.04-X64,icecube/icetray:icetray-prod-current-ubuntu22.04-ARM64
          push: true
#       - name: Create and push manifest images prod 22 04 Date Version
#         uses: Noelware/docker-manifest-action@master # or use whatever version.
#         with:
#           base-image: icecube/icetray:icetray-prod-current-ubuntu22.04-${{ env.current_date }}
#           extra-images: icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu22.04-X64-${{ env.current_date }},icecube/icetray:icetray-prod-${{ env.ICETRAY_VERSION }}-ubuntu22.04-ARM64-${{ env.current_date }}
#           push: true
